French: fra_Latn
German: deu_Latn
Spanish: spa_Latn
Italian: ita_Latn
Chinese: zho_Hans
Russian: rus_Cyrl
Hindi: hin_Deva
Japanese: jpn_Jpan
Korean: kor_Hang
Portuguese: por_Latn
Dutch: nld_Latn
Swedish: swe_Latn
Turkish: tur_Latn
Vietnamese: vie_Latn
